# Generated by Django 3.2.6 on 2021-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='enter details', max_length=500, null=True),
        ),
    ]
