# Generated by Django 3.2.6 on 2021-08-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20210812_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
    ]
