# Generated by Django 3.2.6 on 2021-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/demo.jpg', null=True, upload_to='profiles'),
        ),
    ]
