# Generated by Django 3.2.6 on 2021-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Duration',
            field=models.TextField(choices=[('ONE MONTH', 'ONE MONTH'), ('SIX MONTH', 'SIX MONTH'), ('TWELVE MONTH', 'TWELVE MONTH'), ('CUSTOM', 'CUSTOM')], default=''),
        ),
    ]
