# Generated by Django 3.2.6 on 2021-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proof'),
        ),
    ]
